# Generated by Django 5.2.12 on 2026-07-05 09:36

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acl_checker", "0001_initial"),
        ("authentication", "0026_alter_characterownership_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allowed_states",
                    models.ManyToManyField(
                        blank=True,
                        help_text="States a registered character's account may be in without being flagged. Leave empty to skip this check entirely (a registered character is never flagged purely for its account's state).",
                        to="authentication.state",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
